Preserve data
Lornakaboro/School-library pull request #6
Opened 2023-05-25 18:27 UTC by Lornakaboro

## In this activity I did the following : 

- Stored data in files.
- Run a program using the command line.

2023-05-25 19:07 UTC, GzimAsani requested changes
### Hello, @Lornakaboro            :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with, everything looks good on the console :+1: 

 ## Required Changes 

- [ ] Check the comments below :arrow_double_down: 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N/A



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 19:07 UTC, GzimAsani commented on app.rb
> +      end
- [ ] When I am clicking the number 6 the app throws an error, I know this issue is not part of this millstone but it is very important issue if app breaks, so please check into that. Btw you nailed with the saving data great job :+1:

2023-05-25 19:07 UTC, GzimAsani commented on data_management_system.rb
> +  end
- [ ] After I try to create a person and then close the app with 7 I get the following error, kindly check into that. Also the name on the json file saves differently from what I input 
![image](https://github.com/Lornakaboro/School-library/assets/62705947/7d6496a5-e0e7-4fdc-9190-a00d50c3927c)
![image](https://github.com/Lornakaboro/School-library/assets/62705947/d38096b0-e631-4215-b35e-b347d1d40d71)
- [ ] It saves always the same name as the first one 
![image](https://github.com/Lornakaboro/School-library/assets/62705947/733d32fe-bf83-4fab-937f-6912c9a1b59c)

2023-05-25 19:07 UTC, GzimAsani commented on data_management_system.rb
> +
- [ ] Same error with books, but my new book didn't get saved at all on the json 
![image](https://github.com/Lornakaboro/School-library/assets/62705947/b66cd3c5-454b-4874-9064-20619edbe9c1)

2023-05-25 19:07 UTC, GzimAsani commented on data_management_system.rb
> +  end
- [ ] Even if I just run the app and exit it with 7 automatically one person gets saved, check into this as well please

2023-05-25 19:07 UTC, GzimAsani commented on data_management_system.rb
> +  end
- [ ] I was able to create a rental and saw on console but after exiting the app it wasn't saved on the json, kindly look into that

2023-05-25 22:03 UTC, OyePriscilla requested changes
Hi @Lornakaboro 👏, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Preserve the data app and load preserved data on startup ❎ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 22:03 UTC, OyePriscilla commented on main.rb
>    end
- [ ] I'm so sorry about this, I couldn't access your app functionality due to the error message below 👇. I observed you deleted the data folder, due to this; `people.json` is longer available. **Note: The data folder was there as of last review.**

<img width="569" alt="Untitled" src="https://github.com/Lornakaboro/School-library/assets/103386183/b1cb09ad-baf4-443a-805f-2c8569100b98">

2023-05-25 22:03 UTC, OyePriscilla requested changes
Hi @Lornakaboro 👏, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Preserve the data app and load preserved data on startup ❎ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 08:56 UTC, osamaashraf6 approved these changes
Hi @Lornakaboro 😊, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![MinionsGIF (2)](https://github.com/Lornakaboro/School-library/assets/83360636/98de0396-d1cd-4447-a731-aa4ab4c48141)

## Highlights🎉🎉

- [x] No linter errors present💯
- [x] The PR has a proper title and a descriptive body 👍

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 08:59 UTC, merged